version: "3"
services:
       mongoapp:
           container_name: mongoapp
           image: mongoapp
           restart: always
           build: .
           ports:
             - "8082:8082"
           links:
             - mongo
       mongo:
            container_name: mongo
            image: mongo
            volumes:
               - ./data:/data/db
            ports:
               - '27017:27017'
